### Day 1
< extract.js
GET https://{{urlPrefix}}/1/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 2
< extract.js
GET https://{{urlPrefix}}/2/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 3
< extract.js
GET https://{{urlPrefix}}/3/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 4
< extract.js
GET https://{{urlPrefix}}/4/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 5
< extract.js
GET https://{{urlPrefix}}/5/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 6
< extract.js
GET https://{{urlPrefix}}/6/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 7
< extract.js
GET https://{{urlPrefix}}/7/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 8
< extract.js
GET https://{{urlPrefix}}/8/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt

### Day 9
< extract.js
GET https://{{urlPrefix}}/9/input
Cookie: session={{session}}

> check.js

>>! {{$projectRoot}}/{{dayN}}/input.txt